name: Build and Deploy Jekyll Site

on:
  push:
    branches: [ master ]    # master에 푸시하면 자동 배포
  workflow_dispatch:        # 수동 실행도 허용

permissions:
  contents: write           # gh-pages 브랜치 푸시 권한

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    strategy:
          matrix:
            ruby-version: ['3.1', '3.0', '2.7']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true     # Gemfile.lock 기반으로 자동 install & 캐시

      - name: Build with Jekyll
        env:
          JEKYLL_ENV: production
        run: bundle exec jekyll build --trace

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
