name: Build users JSON
on:
  schedule:
    - cron: "0 * * * *" # 시간 갱신 00:00 UTC 갱신
  workflow_dispatch:

jobs:
  build-users:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install google-analytics-data
      - name: Generate users.json
        env:
          GA4_SA_JSON: ${{ secrets.GA4_SA_JSON }}
          GA4_PROPERTY_ID: ${{ secrets.GA4_PROPERTY_ID }}
        run: |
          python scripts/pull_users.py
      - name: Commit users.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/users.json
          git commit -m "chore: update users.json" || echo "No changes"
          git push
